package jdz.farmKing.upgrades;

public enum UpgradeType {
	NOTHING, RUN_ON_PURCHASE, RUN_ON_TICK, CLICK_DIRECT, CLICK_PERCENT, SEED_DIRECT, SEED_PERCENT, ALIGNMENT_CROP_PERCENT, ALL_CROPS_PERCENT, WORKER_COUNT_DIRECT, WORKER_COUNT_PERCENT, WORKER_PRODUCTION_PERCENT, WORKER_SEED_DIRECT, WORKER_SEED_PERCENT, OFFLINE_PRODUCTION_PERCENT, ONLINE_PRODUCTION_PERCENT, MAIN_CROP_COST_MULTIPLIER, ALL_CROP_COST_MULTIPLIER, AUTO_CLICKS, SEED_COST_MULTIPLIER, SEED_OVER_TIME, CROP_DIRECT;
}
